name: 'ecommerce_analytics'
version: '1.0.0'
config-version: 2

# Profile matches profile name in profiles.yml
profile: 'ecommerce_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configure models
models:
  ecommerce_analytics:
    # Staging models represent simple, clean mappings of raw tables
    staging:
      +schema: staging
      +materialized: view
    # Mart models represent our rich Kimball dimensional tables
    marts:
      +schema: warehouse
      +materialized: table
